### ISSUE TITLE
Have you ever had any issues with the xepersian package?

### ISSUE THREAD

**Issue by ghost** [meysampg/persian_athesis#1]
Hi

If you ever happen to have any question, then please open an issue at [the `xepersian` package issue tracker](https://github.com/persiantex/xepersian/issues) and I will be very happy to help out.

Best wishes, Vafa Khalighi (the author of the `xepersian` package)

**Comment by meysampg** [comment]
@vafakhalighi Thanks for your care Vafa, of course, if I have any problem I'll open issue in xepersian issue tracker. 

P.S. I'll update the readme and repository tag of this repository to refer a link about this note to xepersian repository.

**Comment by ghost** [comment]
Thanks mate
